app/form_blueprint.py
"""Example web view for application factory."""
import jwt
from flask import Blueprint, current_app, request
from flask import render_template, session, url_for, redirect
from app import connection
from core import User_Service
form_x = Blueprint("form_x", __name__)


@form_x.route('/login', methods=['GET', 'POST'])
def login():
    """Login"""
    msg = ''
    if session.get('loggedin') is True:
        msg = f"Welcome Back! {session['username']}"
        return render_template('index.html', msg=msg)
    if request.method == 'POST' and 'username' \
                         in request.form and 'password' in request.form:
        username = request.form['username']
        password = request.form['password']
        user_service = User_Service("User Login")
        result = user_service.login(username=username, password=password)
        conn, cursor, closed, status, message, dt_dict = connection()
        print(conn)
        print(closed)
        print(status)
        print(message)
        print(dt_dict)
        if result['status'] is True:
            data = jwt.decode(result['data']['token'],
                              current_app.config['SECRET_KEY'],
                              algorithms=["HS256"])
            query_check_username = "SELECT * FROM public.user_login_data \
                a inner join user_account b on a.id = b.id WHERE a.id=%s"
            sql_where = (data['id'],)
            cursor.execute(query_check_username, sql_where)
            row = cursor.fetchone()
            session['loggedin'] = True
            session['id'] = data['id']
            session['username'] = row['username']
            session['validation'] = row['email_validation_status_id']
            session['email'] = row['emailaddress']
            if row['email_validation_status_id'] == 2:
                msg = "Akun anda Belum Verifikasi"
            msg = 'Logged in successfully !'
            # return render_template('index.html', msg = msg)
            return redirect(url_for('form_x.index', msg=msg))
        msg = 'Incorrect username / password !'
    return render_template('user/login.html', msg=msg)


@form_x.route('/register', methods=['GET', 'POST'])
def register():
    """register"""
    msg = ''
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        confirmation_password = password
        email = request.form['email']
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        gender = 'm'
        role_id = 1
        data_form = {"username": username,
                     "password": password,
                     "confirmation_password": confirmation_password,
                     "email": email,
                     "first_name": first_name,
                     "last_name": last_name,
                     "gender": gender,
                     "role_id": role_id}
        param = data_form
        try:
            user_service = User_Service("Register Data")
            result = user_service.register(**param)
            if result['status'] is True:
                msg = f" {result['message']} Please Login"
                session['email'] = result['data']['email']
                user_service.resend_confirmation()
            msg = f" {result['message']}"
        except Exception as err:
            msg = f"{err}"
            print(f"{msg}")
    elif request.method == 'POST':
        msg = 'Please fill out the form !'
    return render_template('user/register.html', msg=msg)


@form_x.route('/logout')
def logout():
    session.pop('loggedin', None)
    session.pop('id', None)
    session.pop('username', None)
    session.pop('email', None)
    session.pop('validation', None)
    return redirect(url_for('form_x.login'))


@form_x.route('/')
def index():
    """index_form_blueprint"""
    msg = None
    if session.get("loggedin") is True:
        msg = f"Welcome Back! {session['username']}"
        if session.get("validation") == 2:
            msg = "AKun anda belum verifikasi"
        return render_template('index.html', msg=msg)
    msg = "Silahkan Login"
    return render_template('user/login.html', msg=msg)


@form_x.route("/resend_confirmation", methods=['GET', 'POST'])
def resend_confirmation():
    """resend_confirmation"""
    msg = ''
    user_service = User_Service("User GET DATA")
    result = user_service.resend_confirmation()
    if result['status'] is True:
        msg = "Please Check Your Mail"
        print(f"{ msg } {result['message']}")
    else:
        msg = 'Send Verification Failed, Please Retry'
        print(msg)
    return render_template("index.html", msg=msg)


@form_x.route("/confirm/<token>", methods=["GET"])
def confirm_email(token):
    """confirm_email"""
    session.pop('loggedin', None)
    session.pop('id', None)
    session.pop('username', None)
    session.pop('email', None)
    session.pop('validation', None)
    msg = ''
    user_service = User_Service("User GET DATA")
    result = user_service.confirmation_my_email(token)
    if result['status'] is True:
        msg = "Akun anda sudah Verifikasi"
        session['validation'] = 1
        return render_template(
            'index.html', msg=msg, email=result['data']['email'],
            confirm_email=True)
    msg = result['message']
    return render_template('index.html', msg=msg)


@form_x.route("/resend_forgot_password", methods=['GET', 'POST'])
def resend_forgot_password():
    """resend_forgot_password"""
    msg = ''
    if request.method == 'POST' and 'email' in request.form:
        try:
            email = request.form['email']
            data_form = {"email": email}
            user_service = User_Service("Register Data")
            result = user_service.resend_forgot_pwd(**data_form)
            if result['status'] is True:
                msg = "Check Link in Your Mail"
            else:
                msg = result['message']
        except Exception as err:
            msg = f"{err}"
    elif request.method == 'POST':
        msg = 'Please fill out the form !'
    return render_template("user/form_email_forgot.html", msg=msg)


@form_x.route('/forgot_password/<token>', methods=['GET', 'POST'])
def forgot_password(token):
    """forgot_password"""
    msg = ''
    session['token'] = token
    if request.method == 'POST':
        password = request.form['password']
        confirmation_password = request.form['confirmation_password']
        data_form = {
            "token": token, "password": password,
            "confirmation_password": confirmation_password
            }
        try:
            user_service = User_Service("User GET DATA")
            result = user_service.confirmation_my_password(**data_form)
            if result['status'] is True:
                msg = "Thanks For Changed Password"
                return render_template(
                    'user/change_password.html',
                    msg=msg, email=result['data']['email'], login=True)
            msg = result['message']
        except Exception as err:
            msg = f"{err}"
            print(f"{err}")
    elif request.method == 'POST':
        msg = 'Please fill out the form !'
    return render_template('user/change_password.html', msg=msg, login=False)


@form_x.route("/user_show", methods=["GET", "POST"])
def user_show():
    """user_show"""
    msg = ''
    user_service = User_Service("User GET DATA")
    result = user_service.getuser_detail()
    if result['status'] is True:
        data = result['data']['user']
        msg = request.args.get('msg')
    return render_template('user/user_show.html', data=data, msg=msg)


@form_x.route('/save_edit', methods=['GET', 'POST'])
def save_edit():
    """save_edit"""
    msg = ''
    if request.method == 'POST':
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        date_of_birth = request.form['date_of_birth']
        edit_id = request.args.get('id')
        data_form = {
            "id": edit_id,
            "first_name": first_name,
            "last_name": last_name,
            "date_of_birth": date_of_birth
            }
        try:
            user_service = User_Service("User GET DATA")
            result = user_service.user_change(**data_form)
            if result['status'] is True:
                msg = "Successfully"
                return redirect(url_for('form_x.user_show', id=id, msg=msg))
        except Exception as err:
            msg = f"{err}"
            print(f"{err}")
    elif request.method == 'POST':
        msg = 'Please fill out the form !'
    return render_template('user/user_show.html', msg=msg)

app/templates/user/activate.html
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Soegidev Say Hello!</p>

app/templates/user/base_auth.html
<html>
   <head>
        <meta charset="UTF-8">
        <title> {% block title %}{% endblock %} - Auth </title>
		  <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}"> 
		  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
		  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
		  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">       
   </head>
   <body>
	<div class="wrapper">
			{% block logo %}{% endblock %}
		  	{% block header_form %}{% endblock %}
			{% if msg %}
			  <center><div class="alert alert-warning">{{msg}}</div></center>
			{% endif %}			
			{% block content %}{% endblock %}
			{% block btn_bottom%} {% endblock %}
	</div>
 </body>
</html>
{% block js %}{% endblock %}

app/templates/user/change_password.html
{% extends 'user/base_auth.html' %}
<h1>{% block title %}Change Password {% endblock %}</h1>

{% block logo %}
	<div class="logo">
		<img src="https://www.freepnglogos.com/uploads/coffee-logo-png/coffee-house-creative-logo-vector-download-17.png" alt="">
	</div>
{% endblock %}

{% block header_form %}
	<div class="text-center mt-4 name">
		Change Password
	</div>
	<div class="text-center fs-6">
	Masukkan Password anda yang baru
	</div>
{% endblock %}

{% block content %}
<form class="p-3 mt-3" action="{{ url_for('form_x.forgot_password',token=session.token) }}" method="post">
	 <div class="form-field d-flex align-items-center">
		  <span class="fas fa-key"></span>
		  <input type="password" name="password" id="password" placeholder="Password">
	 </div>
	 <div class="form-field d-flex align-items-center">
		<span class="fas fa-key"></span>
		<input type="password" name="confirmation_password" id="confirm_password" placeholder="confirm_password">
   </div>

	 <div class="text-center">
		<p id="message_pesan"></p>
		<div class="spinner-grow" style="width: 3rem; height: 3rem;" role="status">
		</div>
	 </div>
	 {% if login == False%}
	 <button class="btn mt-3 block_login" onclick="theFunction_change_password()">Change</button>
	 {% endif%}
</form>
{% endblock %}

{% block btn_bottom%} 
	{% if login %}
	<div class="text-center fs-6">
		<a href="{{url_for('form_x.login')}}">Login</a>
	</div>
	{% endif %}
{% endblock %}

{% block js %}
<script type="text/javascript">
    var $loading = $('.spinner-grow').hide();
    function theFunction_change_password () {
        $loading.show();
        someVar="Harap Menunggu"
        document.getElementById('message_pesan').innerText = someVar;
        $('.block_login').addClass("disabled")
        // return true or false, depending on whether you want to allow the `href` property to follow through or not
    }
	$('#password, #confirmation_password').on('keyup', function () {
		if ($('#password').val() == $('#confirmation').val()) {
		  $('#message').html('Matching').css('color', 'green');
		} else 
		  $('#message').html('Not Matching').css('color', 'red');
	  })
</script>
{% endblock %}

app/templates/user/forgot_pwd.html
<p>Please Click below Link For Change Password:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Soegidev Say Hello!</p>

app/templates/user/form_email_forgot.html
{% extends 'user/base_auth.html' %}
<h1>{% block title %}Lupa Password {% endblock %}</h1>

{% block logo %}
	<div class="logo">
		<img src="https://www.freepnglogos.com/uploads/coffee-logo-png/coffee-house-creative-logo-vector-download-17.png" alt="">
	</div>
{% endblock %}

{% block header_form %}
	<div class="text-center mt-4 name">
		Lupa Password
	</div>
	<div class="text-center fs-6">
	Masukkan email anda agar menerima Link untuk reset password, Terimakasih
	</div>
{% endblock %}

{% block content %}
<form class="p-3 mt-3" action="{{ url_for('form_x.resend_forgot_password') }}" method="post">
	 <div class="form-field d-flex align-items-center">
		  <span class="far fa-user"></span>
		  <input id="email" name="email" type="text" placeholder="Email" />
	 </div>
	 <div class="text-center">
		<p id="message_pesan"></p>
		<div class="spinner-grow" style="width: 3rem; height: 3rem;" role="status">
		</div>
	 </div>
	 <button class="btn mt-3 block_login" onclick="theFunction()">Submit</button>
</form>
{% endblock %}

{% block btn_bottom%} 
{% endblock %}

{% block js %}
<script type="text/javascript">
    var $loading = $('.spinner-grow').hide();
    function theFunction_form_forgot () {
        $loading.show();
        someVar="Harap Menunggu"
        document.getElementById('message_pesan').innerText = someVar;
        $('.block_login').addClass("disabled")
    }
</script>
{% endblock %}

app/templates/user/login.html
{% extends 'user/base_auth.html' %}
<h1>{% block title %}Login {% endblock %}</h1>

{% block logo %}
	<div class="logo">
		<img src="https://www.freepnglogos.com/uploads/coffee-logo-png/coffee-house-creative-logo-vector-download-17.png" alt="">
	</div>
{% endblock %}

{% block header_form %}
	<div class="text-center mt-4 name">
		Login
	</div>
{% endblock %}

{% block content %}
<form class="p-3 mt-3" action="{{ url_for('form_x.login') }}" method="post"> 
	<div class="form-field d-flex align-items-center">
		 <span class="far fa-user"></span>
		 <input id="username" name="username" type="text" placeholder="Username" />
	</div>
	<div class="form-field d-flex align-items-center">
		 <span class="fas fa-key"></span>
		 <input type="password" name="password" id="pwd" placeholder="Password">
	</div>
	<div class="text-center">
	   <p id="message_pesan"></p>
	   <div class="spinner-grow" style="width: 3rem; height: 3rem;" role="status">
	   </div>
	</div>
	<button class="btn mt-3 block_login" onclick="theFunction_login()">Login</button>
</form>
{% endblock %}

{% block btn_bottom%} 
	<div class="text-center fs-6">
		<a href="{{url_for('form_x.resend_forgot_password')}}">Forget password?</a> or <a href="{{url_for('form_x.register')}}">Signup</a>
	</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
	var $loading = $('.spinner-grow').hide();
	function theFunction_login () {
		$loading.show();
        someVar="Harap Menunggu"
        document.getElementById('message_pesan').innerText = someVar;
        $('.block_login').addClass("disabled")
    }
</script>
{% endblock %}

app/templates/user/register.html
{% extends 'user/base_auth.html' %}
<h1>{% block title %}Sign Up {% endblock %}</h1>

{% block logo %}
	<div class="logo">
		<img src="https://www.freepnglogos.com/uploads/coffee-logo-png/coffee-house-creative-logo-vector-download-17.png" alt="">
	</div>
{% endblock %}

{% block header_form %}
	<div class="text-center mt-4 name">
		Register
	</div>
{% endblock %}

{% block content %}
   <form class="p-3 mt-3" name="Form" action="{{ url_for('form_x.register') }}" method="post">
      <div class="form-field d-flex align-items-center">
         <span class="far fa-user"></span>
         <input id="username" name="username" type="text" placeholder="Username"/>
      </div>
      <div class="form-field d-flex align-items-center">
         <span class="fas fa-key"></span>
         <input type="password" name="password" id="pwd" placeholder="Password">
      </div>
      <div class="form-field d-flex align-items-center">
         <span class="fas fa-user"></span>
         <input type="text" name="first_name" id="first_name" placeholder="First Name">
      </div>
      <div class="form-field d-flex align-items-center">
         <span class="fas fa-user"></span>
         <input type="text" name="last_name" id="last_name" placeholder="Last Name">
      </div>
      <div class="form-field d-flex align-items-center">
         <span class="fas fa-envelope"></span>
         <input type="email" name="email" id="email" placeholder="Email">
      </div>
      <div class="text-center">
         <p id="message_pesan"></p>
         <div class="spinner-grow" style="width: 3rem; height: 3rem;" role="status">
         </div>
      </div>
      <button id="block_submit" class="btn mt-3" onclick="theFunction_register()">Submit</button>
   </form>
{% endblock %}

{% block btn_bottom%} 
	<div class="text-center fs-6">
		<a href="{{url_for('form_x.resend_forgot_password')}}">Forget password?</a> or <a href="{{url_for('form_x.register')}}">Sign in</a>
   </div>
{% endblock %}

{% block js %}
<script type="text/javascript">
   var $loading = $('.spinner-grow').hide();
   function theFunction_register () {
      var a = document.forms["Form"]["username"].value;
      var b = document.forms["Form"]["password"].value;
      var c = document.forms["Form"]["first_name"].value;
      var d = document.forms["Form"]["last_name"].value;
      var e = document.forms["Form"]["email"].value;
      if (a == null || a == "", b == null || b == "", c == null || c == "", d == null || d == "" ,e == null || e == "") {
         alert("Please Fill All Required Field");
         return false;
      }
      else{
         if(ValidateEmail(e)){
            $loading.show();
            someVar="Harap Menunggu"
            document.getElementById('message_pesan').innerText = someVar;
            $('#block_submit').addClass("disabled")
         }
      }
       // return true or false, depending on whether you want to allow the `href` property to follow through or not
   }
   function ValidateEmail(mail) 
   {
   if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(mail))
   {
      return true;
   }
      alert("You have entered an invalid email address!")
      return false;
   }
</script>
{% endblock %}

app/templates/user/user_show copy 2.html
<html lang="pt_BR">
    <head>
        
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Home </title>
		  <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}"> 
		  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
		  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
		  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">       
    </head>
    <body>
      <div class="wrapper">
			<div class="logo">
				 <img src="https://www.freepnglogos.com/uploads/coffee-logo-png/coffee-house-creative-logo-vector-download-17.png" alt="">
			</div>
            <div class="text-center mt-4 name">
                USER SHOW
           </div>
           <form class="p-3 mt-3" name="Form" action="{{ url_for('form_x.save_edit',id=session.id) }}" method="post">
            {% if msg %}
            <center><div class="alert alert-warning">{{msg}}</div></center>
            {% endif %}
          
             <div class="form-field d-flex align-items-center">
                <span class="far fa-user"></span>
                <input id="first_name" name="first_name" type="text" value="{{data['first_name']}}" required/>
             </div>
             <div class="form-field d-flex align-items-center">
                <span class="far fa-user"></span>
                <input name="last_name" id="last_name" type="text" value="{{data['last_name']}}" required/>
             </div>
             <div class="form-field d-flex align-items-center">
               <span class="fas fa-user"></span>
               <input type="date" name="date_of_birth" id="date_of_birth"value="{{data['date_of_birth']}}"
               min="1950-01-01" max="2030-12-31" Required>
               <!--<input type="date" name="date_of_birth" id="date_of_birth"  required />-->
            </div>
            <div class="text-center">
               <p id="message_pesan"></p>
               <div class="spinner-grow" style="width: 3rem; height: 3rem;" role="status">
                  <span class="sr-only">Loading...</span>
               </div>
            </div>
             <button id="block_submit" class="btn mt-3" onclick="theFunction()">Update</button>
          </form>
          <div class="text-center fs-6">
            <a href="{{url_for('form_x.index')}}">Beranda</a>
        </div>
	  	</div>
    </body>
</html>


<script type="text/javascript">
    var $loading = $('.spinner-grow').hide();
    function theFunction () {
        var a = document.forms["Form"]["date_of_birth"].value;
        if (a == null || a == "") {
            alert("Please Fill All Required Field");
            return false;
        }else{
            $loading.show();
            someVar="Harap Menunggu"
            document.getElementById('message_pesan').innerText = someVar;
            $('.block_logout').addClass("disabled")
        }
    }
</script>

app/templates/user/user_show copy.html
<html lang="pt_BR">
    <head>
        
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Home </title>
		  <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}"> 
		  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
		  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
		  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">       
    </head>
    <body>
      <div class="wrapper">
			<div class="logo">
				 <img src="https://www.freepnglogos.com/uploads/coffee-logo-png/coffee-house-creative-logo-vector-download-17.png" alt="">
			</div>
            <div class="text-center mt-4 name">
                USER SHOW
           </div>
           <form class="p-3 mt-3" name="Form" action="{{ url_for('form_x.save_edit',id=session.id) }}" method="post">
            {% if msg %}
            <center><div class="alert alert-warning">{{msg}}</div></center>
            {% endif %}
          
             <div class="form-field d-flex align-items-center">
                <span class="far fa-user"></span>
                <input id="first_name" name="first_name" type="text" value="{{data['first_name']}}" required/>
             </div>
             <div class="form-field d-flex align-items-center">
                <span class="far fa-user"></span>
                <input name="last_name" id="last_name" type="text" value="{{data['last_name']}}" required/>
             </div>
             <div class="form-field d-flex align-items-center">
               <span class="fas fa-user"></span>
               <input type="date" name="date_of_birth" id="date_of_birth"value="{{data['date_of_birth']}}"
               min="1950-01-01" max="2030-12-31" Required>
               <!--<input type="date" name="date_of_birth" id="date_of_birth"  required />-->
            </div>
            <div class="text-center">
               <p id="message_pesan"></p>
               <div class="spinner-grow" style="width: 3rem; height: 3rem;" role="status">
                  <span class="sr-only">Loading...</span>
               </div>
            </div>
             <button id="block_submit" class="btn mt-3" onclick="theFunction()">Update</button>
          </form>
          <div class="text-center fs-6">
            <a href="{{url_for('form_x.index')}}">Beranda</a>
        </div>
	  	</div>
    </body>
</html>


<script type="text/javascript">
    var $loading = $('.spinner-grow').hide();
    function theFunction () {
        var a = document.forms["Form"]["date_of_birth"].value;
        if (a == null || a == "") {
            alert("Please Fill All Required Field");
            return false;
        }else{
            $loading.show();
            someVar="Harap Menunggu"
            document.getElementById('message_pesan').innerText = someVar;
            $('.block_logout').addClass("disabled")
        }
    }
</script>

app/templates/user/user_show.html
{% extends 'user/base_auth.html' %}
<h1>{% block title %}User Update {% endblock %}</h1>

{% block logo %}
	<div class="logo">
		<img src="https://www.freepnglogos.com/uploads/coffee-logo-png/coffee-house-creative-logo-vector-download-17.png" alt="">
	</div>
{% endblock %}

{% block header_form %}
	<div class="text-center mt-4 name">
		User Update
	</div>
{% endblock %}

{% block content %}
    <form class="p-3 mt-3" name="Form" action="{{ url_for('form_x.save_edit',id=session.id) }}" method="post">    
        <div class="form-field d-flex align-items-center">
            <span class="far fa-user"></span>
            <input id="first_name" name="first_name" type="text" value="{{data['first_name']}}" required/>
        </div>
        <div class="form-field d-flex align-items-center">
            <span class="far fa-user"></span>
            <input name="last_name" id="last_name" type="text" value="{{data['last_name']}}" required/>
        </div>
        <div class="form-field d-flex align-items-center">
        <span class="fas fa-user"></span>
        <input type="date" name="date_of_birth" id="date_of_birth"value="{{data['date_of_birth']}}"
        min="1950-01-01" max="2030-12-31" Required>
        </div>
        <div class="text-center">
        <p id="message_pesan"></p>
        <div class="spinner-grow" style="width: 3rem; height: 3rem;" role="status">
        </div>
        </div>
        <button id="block_submit" class="btn mt-3" onclick="theFunction_Update()">Update</button>
    </form>
{% endblock %}

{% block btn_bottom%} 
	<div class="text-center fs-6">
		<a href="{{url_for('form_x.index')}}">Beranda</a>
   </div>
{% endblock %}


{% block js %}
<script type="text/javascript">
    var $loading = $('.spinner-grow').hide();
    function theFunction_Update () {
        var a = document.forms["Form"]["date_of_birth"].value;
        if (a == null || a == "") {
            alert("Please Fill All Required Field");
            return false;
        }else{
            $loading.show();
            someVar="Harap Menunggu"
            document.getElementById('message_pesan').innerText = someVar;
            $('.block_logout').addClass("disabled")
        }
    }
</script>
{% endblock %}